import { FieldHelper } from "../../shared/helper/field-helper";
import { ObjectHelper } from "../../shared/helper/object-helper";
import { Publication } from "../data/publication";

export class PublicationHelper implements ObjectHelper<Publication,String> {
        withAutoGeneratedId(): boolean { return false;  }
        getId(obj: Publication): string { return obj.id??"?"; };
        getIdKeyName(): string {return "id"; }
        buildEmptyObject(): Publication { return new Publication(); };
        getEntityTypeName(): string { return "Publication";  };
        essentialFieldNames(): string[] {return ["id","titre"]; }
        getFieldHelper(fieldName:string):FieldHelper|null{
                switch(fieldName){
                        case "id" : return new FieldHelper("id");
                        case "title" : return new FieldHelper("titre");
                        //case "change" : return new FieldHelper("change","number",1);
                        default : return null;//NB:FieldHelper(fieldName,fieldType,defaultValue)
                }
        }
}