import { FieldHelper } from "../../shared/helper/field-helper";
import { ObjectHelper } from "../../shared/helper/object-helper";
import { Ressource } from "../data/ressource";


export class RessourceHelper implements ObjectHelper<Ressource,String> {
        withAutoGeneratedId(): boolean { return false;  }
        getId(obj: Ressource): string { return obj.id??"?"; };
        getIdKeyName(): string {return "id"; }
        buildEmptyObject(): Ressource { return new Ressource(); };
        getEntityTypeName(): string { return "Ressource";  };
        essentialFieldNames(): string[] {return ["id","titre"]; }
        getFieldHelper(fieldName:string):FieldHelper|null{
                switch(fieldName){
                        case "id" : return new FieldHelper("id");
                        case "titre" : return new FieldHelper("titre");
                        //other fields not specified here because specific subform is used (upload)
                        default : return null;//NB:FieldHelper(fieldName,fieldType,defaultValue)
                }
        }
}